# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_criar_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Controllers.CriarUsuarioController import CriarUsuarioController


class Ui_TelaCadastroUsuario(object):
    
    
    def __init__(self):
        self.criar_usuario_controller = CriarUsuarioController(self) 
        

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 353)
        MainWindow.setStyleSheet("background-color: rgb(0, 80, 121);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 381, 321))
        self.frame.setStyleSheet("background-color: rgba(0,0,0,0.2)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.inpt_login = QtWidgets.QLineEdit(self.frame)
        self.inpt_login.setGeometry(QtCore.QRect(60, 60, 251, 31))
        self.inpt_login.setStyleSheet("color:#fff; font-size: 16px;")
        self.inpt_login.setText("")
        self.inpt_login.setAlignment(QtCore.Qt.AlignCenter)
        self.inpt_login.setObjectName("inpt_login")
        self.btn_cadastrar = QtWidgets.QPushButton(self.frame)
        self.btn_cadastrar.setGeometry(QtCore.QRect(100, 190, 181, 41))
        self.btn_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastrar.setStyleSheet("QPushButton{color: rgb(255, 255, 255); border-radius: 10px; font-size: 16px; background-color:rgb(0, 0, 10);;}\n"
"\n"
"QPushButton:hover{background-color: #fff; color:black}\n"
"\n"
"")
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.inpt_c_senha = QtWidgets.QLineEdit(self.frame)
        self.inpt_c_senha.setGeometry(QtCore.QRect(60, 140, 251, 31))
        self.inpt_c_senha.setStyleSheet("color:#fff; font-size: 16px;")
        self.inpt_c_senha.setText("")
        self.inpt_c_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inpt_c_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.inpt_c_senha.setObjectName("inpt_c_senha")
        self.inpt_senha = QtWidgets.QLineEdit(self.frame)
        self.inpt_senha.setGeometry(QtCore.QRect(60, 100, 251, 31))
        self.inpt_senha.setStyleSheet("color:#fff; font-size: 16px;")
        self.inpt_senha.setText("")
        self.inpt_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inpt_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.inpt_senha.setObjectName("inpt_senha")
        self.btn_sair = QtWidgets.QPushButton(self.frame)
        self.btn_sair.setGeometry(QtCore.QRect(320, 270, 61, 31))
        self.btn_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sair.setStyleSheet("QPushButton{color: rgb(255, 255, 255); border-radius: 10px; font-size: 16px; background-color:rgb(0, 0, 10);;}\n"
"\n"
"QPushButton:hover{background-color: #fff; color:black}\n"
"\n"
"")
        self.btn_sair.setObjectName("btn_sair")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.btn_cadastrar.clicked.connect(lambda:self.criar_usuario_controller.criar_usuario_adm(self.inpt_login.text(),self.inpt_senha.text(),self.inpt_c_senha.text(),MainWindow))

        self.btn_sair.clicked.connect(lambda:self.criar_usuario_controller.sair(MainWindow))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inpt_login.setPlaceholderText(_translate("MainWindow", "Login"))
        self.btn_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.inpt_c_senha.setPlaceholderText(_translate("MainWindow", "Confirmar senha"))
        self.inpt_senha.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.btn_sair.setText(_translate("MainWindow", "Sair"))
        self.label.setText(_translate("MainWindow", "Cadastro de usuarios"))
