# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_excluir.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Controllers.CriarUsuarioController import CriarUsuarioController


class Ui_TelaExcluirAdmin(object):
    
    
    def __init__(self):
        self.usuario_criar_controller = CriarUsuarioController(self)
        
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 422)
        MainWindow.setStyleSheet("background-color: rgb(0, 80, 121);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_header = QtWidgets.QLabel(self.centralwidget)
        self.lbl_header.setGeometry(QtCore.QRect(150, 10, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header.setFont(font)
        self.lbl_header.setObjectName("lbl_header")
        self.btn_sair = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sair.setGeometry(QtCore.QRect(400, 350, 91, 31))
        self.btn_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sair.setStyleSheet("QPushButton{color: rgb(255, 255, 255); border-radius: 10px; font-size: 16px; background-color:rgb(0, 0, 10);;}\n"
"\n"
"QPushButton:hover{background-color: #fff; color:black}\n"
"\n"
"")
        self.btn_sair.setObjectName("btn_sair")
        self.btn_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_excluir.setGeometry(QtCore.QRect(170, 350, 141, 31))
        self.btn_excluir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excluir.setStyleSheet("QPushButton{color: rgb(255, 255, 255); border-radius: 10px; font-size: 16px; background-color:rgb(0, 0, 10);;}\n"
"\n"
"QPushButton:hover{background-color: #fff; color:black}\n"
"\n"
"")
        self.btn_excluir.setObjectName("btn_excluir")
        self.table_product = QtWidgets.QTableWidget(self.centralwidget)
        self.table_product.setGeometry(QtCore.QRect(20, 40, 441, 291))
        self.table_product.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_product.setRowCount(10)
        self.table_product.setObjectName("table_product")
        self.table_product.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(3, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 505, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        
        
      
        self.usuario_criar_controller.listar_adm()
        
        self.btn_excluir.clicked.connect(lambda:self.usuario_criar_controller.excluir_adm())
        self.btn_sair.clicked.connect(lambda:self.usuario_criar_controller.sair(MainWindow))
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_header.setText(_translate("MainWindow", "Excluir Usuario"))
        self.btn_sair.setText(_translate("MainWindow", "Sair"))
        self.btn_excluir.setText(_translate("MainWindow", "Excluir"))
        item = self.table_product.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_product.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "LOGIN"))
        item = self.table_product.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SENHA"))
        item = self.table_product.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PERMISSÃO"))
