# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_consulta.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Controllers.CriarUsuarioController import CriarUsuarioController


class Ui_TelaConsultar(object):
    
    def __init__(self):
        self.usuario_criar_controller = CriarUsuarioController(self)
             
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(503, 270)
        MainWindow.setStyleSheet("background-color: rgb(0, 80, 121);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_buscar.setGeometry(QtCore.QRect(140, 140, 181, 31))
        self.btn_buscar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_buscar.setStyleSheet("QPushButton{color: rgb(255, 255, 255); border-radius: 10px; font-size: 16px; background-color:rgb(0, 0, 10);;}\n"
"\n"
"QPushButton:hover{background-color: #fff; color:black}\n"
"\n"
"")
        self.btn_buscar.setObjectName("btn_buscar")
        self.btn_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_voltar.setGeometry(QtCore.QRect(400, 190, 91, 31))
        self.btn_voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_voltar.setStyleSheet("QPushButton{color: rgb(255, 255, 255); border-radius: 10px; font-size: 16px; background-color:rgb(0, 0, 10);;}\n"
"\n"
"QPushButton:hover{background-color: #fff; color:black}\n"
"\n"
"")
        self.btn_voltar.setObjectName("btn_voltar")
        self.lbl_header = QtWidgets.QLabel(self.centralwidget)
        self.lbl_header.setGeometry(QtCore.QRect(110, 50, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header.setFont(font)
        self.lbl_header.setObjectName("lbl_header")
        self.inpt_login_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.inpt_login_2.setGeometry(QtCore.QRect(110, 90, 251, 31))
        self.inpt_login_2.setStyleSheet("color:#fff; font-size: 16px;")
        self.inpt_login_2.setText("")
        self.inpt_login_2.setAlignment(QtCore.Qt.AlignCenter)
        self.inpt_login_2.setObjectName("inpt_login_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



        self.btn_buscar.clicked.connect(lambda:self.usuario_criar_controller.consultar_usuario(self.inpt_login_2.text(),MainWindow))
        self.btn_voltar.clicked.connect(lambda:self.usuario_criar_controller.sair(MainWindow))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_buscar.setText(_translate("MainWindow", "Buscar"))
        self.btn_voltar.setText(_translate("MainWindow", "Sair"))
        self.lbl_header.setText(_translate("MainWindow", "Consulta de Usuario"))
        self.inpt_login_2.setPlaceholderText(_translate("MainWindow", "Consulte pelo Login"))
